KEY_USER_ID = 'userid'
KEY_USER_LEVEL = 'userlevel'
KEY_EMAIL = 'email'
KEY_PASSWORD = 'password'
KEY_CODE = 'code'
KEY_SCHOOL_ID = 'schoolid'
KEY_LEAGUE_ID = 'leagueId'
KEY_AI_MODULE = 'aiModule'
KEY_SHIP_PLACEMENT = 'shipPlacement'
KEY_PLAYER = 'player'
KEY_MEMBERS = 'members'
KEY_RANKING = 'ranking'
KEY_WINNER_ID = 'winnerId'
KEY_TEST_ENEMY_TYPE = 'enemy-type'
KEY_TEST_CODE = 'code-test'
KEY_ENEMY_CODE = 'code-enemy'
KEY_SINK = 'sink'

COL_ID = 'ID'
COL_USER_LEVEL = 'userLevel'
COL_UPLOADED_TIME = 'uploadedTime'
COL_FILE_NAME = 'fileName'
COL_SCHOOL_NAME = 'schoolName'
COL_SCHOOL_ID = 'schoolId'
COL_PLACEMENT = 'placement'

UPLOAD_DIR = 'uploads'
UPLOAD_PREFIX = 'with_header_'
LOGS_DIR = 'application/static/logs'
TEMP_DIR = 'tmp/'

#TEMP_CODE_FILE_NAME = 'tmp/temp_code.py'
#TEMP_CODE_FILE_NAME_1 = 'tmp/temp_code_1.py'
#TEMP_CODE_FILE_NAME_2 = 'tmp/temp_code_2.py'
CODE_HEADER_FILE_NAME = 'tmp/code_header'

LEVEL_SCHOOL_ADMIN = 2
LEVEL_GLOBAL_ADMIN = 3